module.exports = {
  AUTHENTICATION_INVALID_CODE: 'AUTHENTICATION_FAILED',
  AUTHENTICATION_INVALID_MESSAGE: 'Missing or Invalid Authentication Header',

  AUTHENTICATION_EXPIRED_CODE: 'AUTHENTICATION_EXPIRED_FAILED',
  AUTHENTICATION_EXPIRED_MESSAGE: 'Authentication Token Already Expired',

  API_KEY_INVALID_CODE: 'API_KEY_AUTHENTICATION_FAILED',
  API_KEY_INVALID_MESSAGE: 'Missing or Invalid Api Key',

  INTERNAL_SERVER_ERROR_CODE: 'INTERNAL_SERVER_ERROR',
  INTERNAL_SERVER_ERROR_MESSAGE: 'INTERNAL_SERVER_ERROR',

  DB_ERROR_CODE: 'DB_ERROR',

  FORM_INVALID_CODE: "FORM_INVALID",

  NOT_FOUND_CODE: "NOT_FOUND",

  PROJECT_NOT_FOUND_CODE: "PROJECT_NOT_FOUND",
  PROJECT_NOT_FOUND_MESSAGE: "Project Not Found",

  PROJECT_TYPE_NOT_FOUND_CODE: "PROJECT_TYPE_NOT_FOUND",
  PROJECT_TYPE_NOT_FOUND_MESSAGE: "Project Type Not Found",

  CLIENT_ID_DOES_NOT_MATCH_CODE: "CLIENT_ID_DOES_NOT_MATCH",
  CLIENT_ID_DOES_NOT_MATCH_MESSAGE: "Client Id does not match with the project",

  PROJECT_TYPE_DOES_NOT_MATCH_CODE: "PROJECT_TYPE_DOES_NOT_MATCH",
  PROJECT_TYPE_DOES_NOT_MATCH_MESSAGE: "Project type does not match with the project",

  PROJECT_CODE_ALREADY_EXIST_CODE: "PROJECT_CODE_ALREADY_EXIST",
  PROJECT_CODE_ALREADY_EXIST_MESSAGE: "Project Code already exist",

  MANAGER_NOT_FOUND_CODE: "MANAGER_NOT_FOUND",
  MANAGER_NOT_FOUND_MESSAGE: "Manager Not Found",

  DIRECTOR_NOT_FOUND_CODE: "DIRECTOR_NOT_FOUND",
  DIRECTOR_NOT_FOUND_MESSAGE: "DIRECTOR Not Found",

  PARTNER_NOT_FOUND_CODE: "PARTNER_NOT_FOUND",
  PARTNER_NOT_FOUND_MESSAGE: "Partner Not Found",
  
}